### ISSUE TITLE
Channel Video Quality on IE

### ISSUE THREAD

**Issue by angelmplus** [mplusmuseum/mplusmuseum-stories#35] opened 2017-10-25 07:47 UTC
![image](https://user-images.githubusercontent.com/28520602/31986359-c5f94824-b99a-11e7-8c00-855e8b859139.png)
![image](https://user-images.githubusercontent.com/28520602/31986383-dc339810-b99a-11e7-8a54-fc07e493ac92.png)

For some reasons, videos quality looks different on IE11 (not as good as on Chrome)
Sometimes it can't be loaded on IE either:

![image](https://user-images.githubusercontent.com/28520602/31986888-a0f0f14c-b99c-11e7-9432-183c789e15ac.png)

**Comment by chrismplus** [comment] 2017-10-25 09:49
Hi @rdunk -- please see @angelmplus 's comments above re: video player time-outs on IE11.

**Comment by rdunk** [comment] 2017-10-26 09:17
The quality issue looks to be specific to the Brightcove platform. It may be serving a different video source depending on browser support for HTML5 videos. May be worth speaking to Brightcove directly about this.

As for the video not loading at all, Brightcove [has some more information here](https://support.brightcove.com/display-error-messages-plugin). Again, I imagine this is related to issues connecting to the Brightcove platform itself. @angelmplus can you confirm this only happens on IE?

Will leave this open until we have some more information.

**Comment by chrismplus** [comment] 2017-10-27 07:41
Hi @rdunk -- I can confirm this happens on IE and as described in [Issue 17](https://github.com/mplusmuseum/mplusmuseum-stories/issues/17).

**Comment by rdunk** [comment] 2017-10-27 15:44
It looks like we have two separate issues regarding videos failing:

1. The player does not instantiate at all.
2. The player instantiates but then times out.

If you are able to debug this at all using the Network tab of the browser's Developer Tools that would be a great help (I can give further instructions if needed or demonstrate in our next meeting). 

I am unable to replicate either error on our end, and would like to check that all network requests to the Brightcove platform are succeeding so we can identify if the issues are M+ Stories or Brightcove specific.

**Comment by chrismplus** [comment] 2017-10-30 01:34
Noted--let's go over this in our next meeting.

**Comment by chrismplus** [comment] 2017-10-30 03:32
@rdunk -- see console error and front-end result of non-responsive player. 

![video-console-error](https://user-images.githubusercontent.com/26731347/32153503-f76ee3f4-bd65-11e7-810c-078cd0bd5f9d.jpg)
![video-player-error](https://user-images.githubusercontent.com/26731347/32153504-f79b1370-bd65-11e7-9858-ad51eda4fc1d.jpg)

**Comment by chrismplus** [comment] 2017-11-23 04:12
@rdunk -- is this enough info to be of use to Brightcove for this task?

**Comment by rdunk** [comment] 2017-11-23 17:05
Difficult to say, the error messages we can see are all pretty vague but maybe they'll be able to tell more from the session IDs. Still awaiting a reply, will chase.

**Comment by chrismplus** [comment] 2017-11-29 02:43
Duplicate. Outlined in #69. Closing.

**Closed by chrismplus** 2017-11-29 02:43 UTC
Labels: brightcove, bug, duplicate
