### ISSUE TITLE
Hyperlinking in Chinese-language image caption

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#76] opened 2017-11-03 08:03 UTC
Unable to place a hyperlink in the Chinese-language image caption element within the blog. This does work on the English language caption element, however. It also works on the Chinese-language caption field on the Brightcove video element too.

**Comment by rdunk** [comment] 2017-11-03 11:18
Not able to reproduce this, think I'm probably misunderstanding. Can you give me any more information? For reference:

Under an image (EN)
<img width="935" alt="screen shot 2017-11-03 at 11 15 40" src="https://user-images.githubusercontent.com/8467307/32371379-84308e6c-c088-11e7-8da6-45b7f29583d6.png">

Under an image (TC)
<img width="930" alt="screen shot 2017-11-03 at 11 15 48" src="https://user-images.githubusercontent.com/8467307/32371380-844c1bb4-c088-11e7-80d1-8c9bfa227d8a.png">

Lightbox caption (EN)
<img width="933" alt="screen shot 2017-11-03 at 11 16 25" src="https://user-images.githubusercontent.com/8467307/32371382-8bed6986-c088-11e7-83bd-937fbd7fe332.png">

Lightbox caption (TC)
<img width="929" alt="screen shot 2017-11-03 at 11 16 33" src="https://user-images.githubusercontent.com/8467307/32371384-8c0195a0-c088-11e7-8c8b-910fe2207dc1.png">

**Comment by chrismplus** [comment] 2017-11-06 01:54
This is happening on the live blog site: 

**URL:** https://stories.mplus.org.hk/tc/blog/whats-going-on-at-the-m-construction-site-november-2017

**CMS:**
![image](https://user-images.githubusercontent.com/26731347/32421993-4f806172-c2d8-11e7-863f-68d032d2408f.png)

**Front-end:** 
![image](https://user-images.githubusercontent.com/26731347/32422004-62816eb0-c2d8-11e7-9b2a-bae04ecc93bb.png)

**Comment by rdunk** [comment] 2017-11-06 09:21
Ah, I see. Must be the markdown formatter. I was inserting HTML hyperlinks. Will investigate.

**Comment by rdunk** [comment] 2017-11-07 17:19
Seems to be a CMS issue, trying to get it resolved.

For the time being inserting HTML markup instead of markdown should work correctly.

**Comment by chrismplus** [comment] 2017-11-08 02:34
Noted. HTML working--it would be good to get the markdown working too though so we don't have to worry about switching between methods. 

I'll leave this open for now.

**Comment by rdunk** [comment] 2017-11-08 09:28
Totally agree, will try and get this resolved ASAP.

**Comment by chrismplus** [comment] 2017-11-23 04:06
Moving to 'Ready'.

**Comment by rdunk** [comment] 2017-11-29 16:52
Just implemented a fix for this, markdown works for image captions in all languages now.

**Closed by rdunk** 2017-11-29 16:52 UTC
Labels: bug
